import React from 'react';
import { Calendar, FileText } from 'lucide-react';
import { Acquisition } from '../../types';
import { SchemaBinding } from '../../hooks/useSchemaService';
import CombinedComplianceView from './CombinedComplianceView';

interface ComplianceReportProps {
  acquisitions: Acquisition[];
  schemaPairings: Map<string, SchemaBinding>;
  className?: string;
  getSchemaContent: (id: string) => Promise<string | null>;
  getSchemaAcquisition: (binding: SchemaBinding) => Promise<Acquisition | null>;
  hideUnknownStatus?: boolean;
}

const ComplianceReport: React.FC<ComplianceReportProps> = ({
  acquisitions,
  schemaPairings,
  className = '',
  getSchemaContent,
  getSchemaAcquisition,
  hideUnknownStatus = false
}) => {
  const currentDate = new Date().toLocaleDateString('en-US', {
    year: 'numeric',
    month: 'long',
    day: 'numeric',
    hour: '2-digit',
    minute: '2-digit'
  });

  return (
    <div className={`bg-white ${className}`}>
      {/* Report Header */}
      <div className="border-b-2 border-gray-200 pb-6 mb-8">
        <h1 className="text-3xl font-bold text-gray-900 mb-2">dicompare report</h1>
        <div className="flex items-center space-x-6 text-sm text-gray-600">
          <div className="flex items-center space-x-2">
            <Calendar className="h-4 w-4" />
            <span>Generated: {currentDate}</span>
          </div>
          <div className="flex items-center space-x-2">
            <FileText className="h-4 w-4" />
            <span>{acquisitions.length} acquisition{acquisitions.length !== 1 ? 's' : ''} analyzed</span>
          </div>
        </div>
      </div>

      {/* Acquisition Details */}
      <div className="space-y-8">
        {acquisitions.map((acquisition) => {
          const pairing = schemaPairings.get(acquisition.id);
          if (!pairing) return null;

          return (
            <div key={acquisition.id} className="border border-gray-200 rounded-lg p-6 break-inside-avoid">
              {/* Acquisition Header */}
              <div className="mb-4 pb-3 border-b border-gray-200">
                <h2 className="text-xl font-semibold text-gray-900 mb-1">
                  Schema: {pairing.schema.name}
                </h2>
                <p className="text-sm text-gray-600">Protocol: {acquisition.protocolName}</p>
              </div>

              {/* Use CombinedComplianceView with printMode */}
              <CombinedComplianceView
                acquisition={acquisition}
                pairing={pairing}
                getSchemaContent={getSchemaContent}
                getSchemaAcquisition={getSchemaAcquisition}
                printMode={true}
                hideUnknownStatus={hideUnknownStatus}
              />
            </div>
          );
        })}
      </div>

      {/* Report Footer */}
      <div className="mt-8 pt-6 border-t border-gray-200 text-center text-xs text-gray-500">
        <p>This report was generated by dicompare on {currentDate}</p>
      </div>
    </div>
  );
};

export default ComplianceReport;
